### ISSUE TITLE
TrippyTokens on Dogeparty

### ISSUE THREAD

**Issue by avaliantone** [AwesomeLabs/token-art#1]
Writing to see if you can help me get my project TrippyTokens on Dogeparty config file setup

-Ernest

**Comment by btroia** [comment]
@Valiant401 ok, we've set up a [starter config](https://github.com/AwesomeLabs/token-art/tree/main/blockchains/dogeparty/trippy-tokens) for you to use! Let us know if you have any questions/issues

**Comment by avaliantone** [comment]
json file updated & pull request sent
