### ISSUE TITLE
Collection Request: Dogermint on Dogeparty

### ISSUE THREAD

**Issue by nutildah** [AwesomeLabs/token-art#3]
Would like to add Dogermint tokens as a collection on token.art. Thank you!

https://dogermint.com/

**Comment by btroia** [comment]
@nutildah Ok, we've set up a [starter config](https://github.com/AwesomeLabs/token-art/blob/main/blockchains/dogeparty/dogermint/) for you to use! Let us know if you have any questions/issues

**Comment by nutildah** [comment]
Thanks, much appreciated! Will do.
