### ISSUE TITLE
Rare Ordinals on Counterparty

### ISSUE THREAD

**Issue by subterranean1** [AwesomeLabs/token-art#5]
Hi,

I'd like to volunteer to be a curator for this collection.

**Comment by btroia** [comment]
@subterranean1 ok, we've set up a [starter config](https://github.com/AwesomeLabs/token-art/tree/main/blockchains/counterparty/rare-ordinal-directory) for you to use! Let us know if you have any questions/issues

**Comment by subterranean1** [comment]
Hi Bob,

I'm all finished with the Rare Ordinals json. I can't mark it "ready for
review" because there is a warning message: 1 workflow awaiting approval.
Can you take a look?

Thanks

**Comment by subterranean1** [comment]
https://github.com/subterranean1/token-art/blob/patch-1/blockchains/counterparty/rare-ordinal-directory/rare-ordinal-directory.json

**Comment by btroia** [comment]
Hi! Yes we have to run the workflow check to validate JSON, etc. We'll do a final review shortly to ensure all links to images, etc. are working then merge!

**Comment by btroia** [comment]
@subterranean1 can you go through the file and make sure extra whitespace is removed from any links? For example, noticed an extra space/tab in the `primary_image` value below:

```
...
  "edition": "Card 2",
  "name": "INSCRIBEPEPE",
   "images": {
     "primary": "	https://arweave.net/58iosXJ-qQkLAKWX-rbhnfkNr0oSxiWHCEpp3wfldbw/INSCRIBEPEPE.png",
      "other": [""]
    },
```

**Comment by subterranean1** [comment]
Sorry! Do I still need to do this? It looks like it’s merged On Feb 26, 2023, at 7:50 AM, Bob Troia ***@***.***> wrote:﻿
@subterranean1 can you go through the file and make sure extra whitespace is removed from any links? For example, noticed an extra space/tab in the primary_image value below:
...
      "edition": "Card 2",
          "name": "INSCRIBEPEPE",
          "images": {
            "primary": "	https://arweave.net/58iosXJ-qQkLAKWX-rbhnfkNr0oSxiWHCEpp3wfldbw/INSCRIBEPEPE.png",
            "other": [""]
          },
          ```


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by subterranean1** [comment]
Hi,

I removed the extra whitespaces and also added series 4 (which was released
today).

Thanks

**Comment by btroia** [comment]
Great! However, looks like it's failing JSON validation (there's an extra `}` and an extra comma after the last asset) - I'll take care of this before I do the merge but in the future you'll want to jsonlint the file to make sure it's valid (you can use [jsonlint.com](https://jsonlint.com) or [DuckDuckGo's built-in validator](https://duckduckgo.com/?q=jsonlint))

**Comment by subterranean1** [comment]
Thanks for the heads up. I don’t use GitHub very often so I’m still learning On Feb 27, 2023, at 11:49 AM, Bob Troia ***@***.***> wrote:﻿
Great! However, looks like it's failing JSON validation (there's an extra } and an extra comma after the last asset) - I'll take care of this before I do the merge but in the future you'll want to jsonlint the file to make sure it's valid (you can use jsonlint.com or DuckDuckGo's built-in validator)

**Comment by btroia** [comment]
@subterranean1 Ok, config should be live!

**Comment by subterranean1** [comment]
Thank you! It looks great in the app. Today I fixed (3) bad image links and added (10) new series 4 cards. I then ran it through jsonlint.com and it came back "valid JSON"

**Comment by subterranean1** [comment]
Hi! Can you take a look at my latest pr? It's got some link updates and new cards. Thanks

**Comment by btroia** [comment]
Great! Will get to it shortly thanks!

**Comment by subterranean1** [comment]
Hello, I corrected the extra spacing issue. Can you please have a look at my Bitcoin Stamps request as well? I have verified it is a valid .json. 

Thanks

**Comment by subterranean1** [comment]
Thank you! I found a syntax error in series 5 of Rare Ordinals, so I opened
a new PR. I also created .jsons for Bitcoin Stamps and Penisium. They are
ready to go too.

Thanks again
