### ISSUE TITLE
Historical Counterparty project - Penisium

### ISSUE THREAD

**Issue by subterranean1** [AwesomeLabs/token-art#8]
Hi, 
How would you feel about adding a slightly NSFW counterparty project called Penisium? Here are the cards: https://penisium.org/cards/ (note they lost their https certificate, but the page works). I would be happy to create the json file for the project if approved.

Thanks

**Comment by btroia** [comment]
@subterranean1 Thanks, we'll look into it. At first glance, we may have issues accessing non-https urls in our app due to security settings. Will keep you posted 👍

**Comment by subterranean1** [comment]
I wouldn’t use that page for project images, I just wanted you to see what the cards looked like 🙂On Feb 28, 2023, at 6:57 PM, Bob Troia ***@***.***> wrote:﻿
@subterranean1 Thanks, we'll look into it. At first glance, we may have issues accessing non-https urls in our app due to security settings. Will keep you posted 👍
